title: "Elliott's Computer"
email: elliottcost@gmail.com
author: Elliott Cost
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: UA-81186367-3

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
- scope:
    path: ''
  values:
    layout: 
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    lang: en